package:
  name: most
  version: 0.3.8

source:
  path: .

build:
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  host:
    - python >=3.11,<3.12
    - pip
    - setuptools >=68
    - wheel

  run:
    - python >=3.11,<3.12
    
    # bio tools
    - snakemake >=9.23.1
    - biopython >=1.87
    - bbmap >=39.81
    - cutadapt >=5.2
    - chromap >=0.3.2
    - samtools >=1.23
    - star >=2.7.9a
    - pigz >=2.8

    # scientific stack
    - numpy >=2.2
    - pandas >=2.3
    - scipy >=1.15
    - matplotlib >=3.10
    - python-kaleido >=0.2.1
    - plotly >=5.24.1

    # utils
    - pyyaml >=6.0.3
    - typer 
    - pydantic >=2.13.2

test:
  imports:
    - most

  commands:
    - most --help

about:
  home: https://github.com/sansh0u/MOST
  summary: "Multi-omics Spatial Toolkit"
  license: GPL-3.0