package:
  name: most
  version: 0.1.8

source:
  path: .

build:
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - pip
    - setuptools

  host:
    - python
    - pip
    - setuptools

  run:
    - python
    
    # bio tools
    - snakemake >=9.23.1
    - biopython >=1.87
    - bbmap >=39.81
    - cutadapt
    - chromap >=0.3.2
    - samtools >=1.23
    - star >=2.7
    - openjdk >=11
    - pysam >=0.22,<0.23
    - biscuit

    # scientific stack
    - numpy >=2.2
    - pandas >=2.3
    - scipy >=1.15
    - matplotlib >=3.10
    - pyarrow >=23
    - h5py >=3.16
    - anndata >=0.11

    # utils
    - pyyaml >=6.0.3
    - tqdm
    - typer
    - pydantic >=2.13.2
    - beautifulsoup4
    - opencv

test:
  imports:
    - most

  commands:
    - most --help

about:
  home: https://github.com/sansh0u/MOST
  summary: "Multi-omics Spatial Toolkit"
  license: GPL-3.0