Project: #test

Method: ATAC #ATAC/RNA

Sequence_file:
  file1: /mnt/d/prog/SRR32966850_1.fastq.gz
  file2: /mnt/d/prog/SRR32966850_2.fastq.gz
Reference:
  index_file: /home/sanshou/project/toolkit/toolkit/index/GRCm38.primary_assembly.genome.index
  fa_file: /home/sanshou/project/toolkit/toolkit/index/human/GRCh38.primary_assembly.genome.fa
  gtf_file: /home/sanshou/project/toolkit/toolkit/index/human/gencode.v48.primary_assembly.annotation.gtf
  star_index: /home/sanshou/project/toolkit/star_index1

Barcode:

Out_dir:
  dir: /home/sanshou/project/toolkit/output/

Threads: 8

Advanced:
  primer: #CAAGCGTTGGCTTCTCGCATCT
  linker1: #GTGGCCGATGTTTCGCATCGGCGTACGACT
  linker2: #ATCCACGTGCTTGAGAGGCCAGAGCATTCG
  UMI: #umi起始位置
  hdist: #3
  rna_lib: #pcr/illumina
  adapter: #AAGCAGTGGTATCAACGCAGAGTGAATGGG
  adapter_mismatch: